services:
  client:
    restart: unless-stopped
    container_name: doc-frontend
    image: softvence/doc-client:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      # ADD THIS SECTION: Pass variables as build arguments
      args:
        - NODE_ENV=production
        - NEXT_TELEMETRY_DISABLED=1
        - NEXT_PUBLIC_API_BASE_URL=https://prod.weightlossmdcherrycreek.com
        - NEXT_PUBLIC_CLOVER_PAKMS_KEY=${NEXT_PUBLIC_CLOVER_PAKMS_KEY:-dbbe599d5dbe806a9809adc246f3270f}
        - NEXT_PUBLIC_CLOVER_MERCHANT_ID=${NEXT_PUBLIC_CLOVER_MERCHANT_ID:-C233HRQ3TW7N1}
        - NEXT_PUBLIC_CLOVER_ENV=${NEXT_PUBLIC_CLOVER_ENV:-development}

    # Keep environment for runtime (in case the app reads them again at runtime)
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_BASE_URL=https://prod.weightlossmdcherrycreek.com
      - NEXT_PUBLIC_CLOVER_PAKMS_KEY=${NEXT_PUBLIC_CLOVER_PAKMS_KEY:-dbbe599d5dbe806a9809adc246f3270f}
      - NEXT_PUBLIC_CLOVER_MERCHANT_ID=${NEXT_PUBLIC_CLOVER_MERCHANT_ID:-C233HRQ3TW7N1}
      - NEXT_PUBLIC_CLOVER_ENV=${NEXT_PUBLIC_CLOVER_ENV:-development}
      - API_BASE_URL=http://app_live_blue:5056/api/v1 # Change 'server' and '5000' to your backend service name and port if needed

    ports:
      - "3000:3000"
    networks:
      - doc_release

networks:
  doc_release:
    external: true
    name: doc-backend_doc_release
